# Użyj obrazu bazowego Kafka Connect od Confluent
FROM confluentinc/cp-kafka-connect-base:latest

# Zainstaluj Kafka Connect JDBC Connector
RUN confluent-hub install --no-prompt confluentinc/kafka-connect-jdbc:5.4.1

